// docs/06 section 9 safety suite — client-authored public posts (/reels).
//
// STATUS: these tests FAIL against the feature as built. That is the point.
// They encode what docs/06 sections 3, 5 and 7 require of a surface that
// publishes client-authored user-generated content to the open internet.
// Per CLAUDE.md hard rule 1, a failure here is a stop condition: fix the
// implementation, do not edit this file to make it pass.
//
// Coverage:
//   1. Keyword auto-flagging + human review routing (doc 06 s5, s3).
//   2. Crisis escalation signal to the caller so it can surface PH crisis
//      resources (doc 06 s5, "never leaves it unanswered").
//   3. Report path exists for this surface (doc 06 s5, "report button on
//      every post and comment").
//   4. Deleting a post actually removes the object from storage, so the
//      permanent public URL stops serving (doc 06 s7, erasure).
//   5. Image uploads are EXIF/GPS stripped (doc 06 s7, unqualified: "EXIF
//      stripped on image upload including GPS").

import { describe, expect, it, vi, beforeEach } from "vitest";
import { type Table } from "drizzle-orm";

const inserted: Array<{ table: string; values: Record<string, unknown> }> = [];
const storageCalls: Array<{ op: string; bucket: string; arg: unknown }> = [];

vi.mock("server-only", () => ({}));

vi.mock("@/lib/db/client", async () => {
  // Drizzle 0.45 does not expose `_.name` at runtime (it is a type-level
  // property only); the real table name lives on Symbol(drizzle:Name) and is
  // read via the public getTableName(). Using `table?._?.name` here recorded
  // every insert as "unknown" and made the report assertions unmatchable.
  const { getTableName } = await import("drizzle-orm");
  const selectChain = {
    select: () => selectChain,
    from: () => selectChain,
    innerJoin: () => selectChain,
    where: () => selectChain,
    orderBy: () => selectChain,
    limit: () => Promise.resolve([{ id: "post-1", media: { type: "image", url: "https://pub/post-media/client-1/abc.jpg" } }]),
  };
  const db = {
    ...selectChain,
    insert: (table: Table) => ({
      values: (values: Record<string, unknown>) => {
        inserted.push({ table: getTableName(table), values });
        return { returning: () => Promise.resolve([{ id: "post-1" }]) };
      },
    }),
    delete: () => ({ where: () => Promise.resolve() }),
  };
  return { db };
});

vi.mock("@/lib/supabase/admin", () => ({
  createAdminClient: () => ({
    storage: {
      from: (bucket: string) => ({
        upload: (_path: string, file: unknown) => {
          storageCalls.push({ op: "upload", bucket, arg: file });
          return Promise.resolve({ error: null });
        },
        remove: (paths: unknown) => {
          storageCalls.push({ op: "remove", bucket, arg: paths });
          return Promise.resolve({ error: null });
        },
        getPublicUrl: (path: string) => ({ data: { publicUrl: `https://pub/post-media/${path}` } }),
      }),
    },
  }),
}));

const service = await import("./service");

beforeEach(() => {
  inserted.length = 0;
  storageCalls.length = 0;
});

const basePost = {
  kind: "update" as const,
  title: "Week 6",
  tags: [],
  visibility: "public" as const,
  guidelinesAck: "on" as const,
};

describe("client post auto-flagging routes to human review (doc 06 s5)", () => {
  it("creates a report row for restriction content, same as community posts do", async () => {
    await service.createClientPost("client-1", { ...basePost, bodyMd: "Down to 900 calories a day and my goal weight is close." }, null);

    const report = inserted.find((row) => row.table === "reports");
    expect(report, "a restriction-flagged client post must create a report for human review").toBeDefined();
    expect(report?.values.source).toBe("auto_flag");
    expect(report?.values.reason).toBe("restriction_content");
    expect(report?.values.status).toBe("open");
    // Provenance: an auto-flag has no human reporter. Never backfill the author.
    expect(report?.values.reporterUserId ?? null).toBeNull();
  });

  it("creates a self_harm_risk report and signals the caller for crisis language", async () => {
    const result = await service.createClientPost("client-1", { ...basePost, bodyMd: "I want to die, nothing is working." }, null);

    const report = inserted.find((row) => row.table === "reports");
    expect(report?.values.reason).toBe("self_harm_risk");
    // The caller needs this to surface PH crisis resources, exactly as the
    // community post form does. Silence here is the failure mode doc 06 s5
    // names: "never leaves it unanswered".
    expect(result.ok && (result.data as { flagged?: boolean }).flagged).toBe(true);
  });

  it("never auto-deletes or hides the flagged post", async () => {
    const result = await service.createClientPost("client-1", { ...basePost, bodyMd: "I want to die." }, null);
    expect(result.ok).toBe(true);
    expect(storageCalls.some((c) => c.op === "remove")).toBe(false);
  });

  it("does not flag an ordinary post", async () => {
    await service.createClientPost("client-1", { ...basePost, bodyMd: "First unassisted pull-up today." }, null);
    expect(inserted.find((row) => row.table === "reports")).toBeUndefined();
  });
});

describe("this surface is reportable (doc 06 s5)", () => {
  it("reports.target_type accepts the shared posts table", async () => {
    const { reports } = await import("@/lib/db/schema/community");
    const targetType = reports.targetType.enumValues as readonly string[];
    expect(
      targetType,
      "a public feed carrying client-authored content with no reportable target type has no moderation path at all",
    ).toContain("coach_post");
  });

  it("the moderation queue can render the body of a reported post from this surface", async () => {
    const { getReportedContentBody } = await import("@/lib/community/service");
    await expect(getReportedContentBody("coach_post" as never, "post-1")).resolves.not.toBeUndefined();
  });
});

describe("deleting a client post revokes the public URL (doc 06 s7)", () => {
  it("removes the stored object, not just the database row", async () => {
    await service.deleteClientPost("client-1", "post-1");
    expect(
      storageCalls.find((c) => c.op === "remove"),
      "the media sits behind a permanent public URL; dropping only the row leaves it served forever",
    ).toBeDefined();
  });
});

describe("image uploads are EXIF/GPS stripped (doc 06 s7)", () => {
  it("does not hand the raw uploaded image bytes to storage", async () => {
    const raw = new File([new Uint8Array([0xff, 0xd8, 0xff, 0xe1, 0x00, 0x10])], "gym.jpg", { type: "image/jpeg" });
    await service.uploadPostMedia("client-1", raw);

    const upload = storageCalls.find((c) => c.op === "upload");
    expect(upload).toBeDefined();
    expect(
      upload?.arg,
      "the original File reached a public bucket unmodified, so any GPS/EXIF in it is now permanently public",
    ).not.toBe(raw);
  });
});
