// docs/06 section 9 safety suite — moderation takedown for reported community
// content.
//
// Regression coverage for a fix: previously a moderator reviewing a reported
// community post or comment could only "mark actioned" — the underlying
// content, including any media file, stayed live forever, and the admin
// queue couldn't even see the reported media (only caption text).
//
// Fixed in lib/community/service.ts:
//   - deleteCommunityPost reuses deletePostMediaObject (the same takedown
//     path already proven for coach_post/reels) so a public media URL stops
//     serving once a post is taken down (docs/06 section 7, erasure).
//   - deleteCommunityComment is a row delete only — comments have no media
//     column, so it must never attempt a storage call.
//   - getReportedContentBody returns `{ body, media }` instead of body text
//     alone, so a moderator can actually see what they're reviewing.
//
// Blocks merges (CLAUDE.md hard rule 1) — do not edit this file to make it
// pass. Fix lib/community/service.ts instead.

import { describe, expect, it, vi, beforeEach } from "vitest";
import { type Table } from "drizzle-orm";

const inserted: Array<{ table: string; values: Record<string, unknown> }> = [];
const deletedTables: string[] = [];
const deletePostMediaObject = vi.fn(async (_media: unknown) => {});

vi.mock("server-only", () => ({}));

const POST_ROW = { id: "post-1", media: { type: "image" as const, url: "https://pub/post-media/communities/comm-1/abc.jpg" } };
const COMMENT_ROW = { id: "comment-1" };

vi.mock("@/lib/db/client", async () => {
  const { getTableName } = await import("drizzle-orm");
  const selectChain = {
    select: (_projection: Record<string, unknown>) => ({
      from: (table: Table) => {
        const name = getTableName(table);
        return {
          from: () => selectChain,
          innerJoin: () => selectChain,
          leftJoin: () => selectChain,
          where: () => ({
            limit: () => {
              if (name === "community_posts") {
                // Row shape adapts to whichever columns the caller projected
                // (deleteCommunityPost selects id+media, getReportedContentBody
                // selects bodyMd+media) — both are present on this fixture row.
                return Promise.resolve([{ ...POST_ROW, bodyMd: "reported caption" }]);
              }
              if (name === "community_comments") {
                return Promise.resolve([{ ...COMMENT_ROW, bodyMd: "reported comment text" }]);
              }
              return Promise.resolve([]);
            },
          }),
        };
      },
    }),
  };
  const db = {
    select: selectChain.select,
    insert: (table: Table) => ({
      values: (values: Record<string, unknown>) => {
        inserted.push({ table: getTableName(table), values });
        return { returning: () => Promise.resolve([{ id: "new-id" }]) };
      },
    }),
    delete: (table: Table) => ({
      where: () => {
        deletedTables.push(getTableName(table));
        return Promise.resolve();
      },
    }),
  };
  return { db };
});

vi.mock("@/lib/content/service", () => ({
  deletePostMediaObject: (media: unknown) => deletePostMediaObject(media),
  uploadPostMedia: vi.fn(),
}));

const service = await import("./service");

beforeEach(() => {
  inserted.length = 0;
  deletedTables.length = 0;
  deletePostMediaObject.mockClear();
});

describe("deleteCommunityPost takes down media, comments, and the post (doc 06 s7)", () => {
  it("calls the shared storage-deletion function with the post's media", async () => {
    const result = await service.deleteCommunityPost("post-1");

    expect(result.ok).toBe(true);
    expect(
      deletePostMediaObject,
      "the post-media bucket is public; taking down only the row leaves an already-shared media URL serving forever",
    ).toHaveBeenCalledWith(POST_ROW.media);
  });

  it("deletes child comments before the post row (FK)", async () => {
    await service.deleteCommunityPost("post-1");

    expect(deletedTables).toContain("community_comments");
    expect(deletedTables).toContain("community_posts");
    expect(deletedTables.indexOf("community_comments")).toBeLessThan(deletedTables.indexOf("community_posts"));
  });
});

describe("deleteCommunityComment is a row delete only (doc 06 s7)", () => {
  it("deletes the comment row", async () => {
    const result = await service.deleteCommunityComment("comment-1");

    expect(result.ok).toBe(true);
    expect(deletedTables).toContain("community_comments");
    expect(deletedTables).not.toContain("community_posts");
  });

  it("never attempts a storage deletion, since comments have no media column", async () => {
    await service.deleteCommunityComment("comment-1");

    expect(
      deletePostMediaObject,
      "community_comments has no media column today; if a future schema change adds one, this call must start happening again — a silent no-op here would leave takedown media live",
    ).not.toHaveBeenCalled();
  });
});

describe("getReportedContentBody surfaces media, not just a caption (doc 06 s5)", () => {
  it("returns both body and media for a community_post target", async () => {
    const result = await service.getReportedContentBody("community_post", "post-1");

    expect(result.body).toBe("reported caption");
    expect(
      result.media,
      "a moderator deciding whether to take a photo or video down cannot judge it from the caption alone",
    ).toEqual(POST_ROW.media);
  });

  it("returns a null media for a community_comment target (comments carry no media)", async () => {
    const result = await service.getReportedContentBody("community_comment", "comment-1");

    expect(result.body).toBe("reported comment text");
    expect(result.media).toBeNull();
  });
});
