// A small starter exercise library for local dev and the seed script. The
// full 300-500 exercise global library is Phase 1 scope (docs/07-roadmap.md).

export interface SeedExercise {
  name: string;
  primaryMuscle: string;
  secondaryMuscles?: string[];
  movementPattern:
    | "squat"
    | "hinge"
    | "h_push"
    | "h_pull"
    | "v_push"
    | "v_pull"
    | "lunge"
    | "carry"
    | "rotation"
    | "anti_rotation"
    | "isolation"
    | "conditioning";
  equipment: string[];
  isUnilateral?: boolean;
  loadingType: "external" | "bodyweight" | "bw_plus_load" | "time" | "distance" | "calories";
  difficulty: number;
  substitutionGroup?: string;
  contraindications?: string[];
  cues: string[];
}

export const SEED_EXERCISES: SeedExercise[] = [
  // --- Original 36 ---
  { name: "Back Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", contraindications: ["lower_back", "knee"], cues: ["Brace before you break the hips", "Knees track over toes"] },
  { name: "Goblet Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], movementPattern: "squat", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Elbows inside knees at the bottom"] },
  { name: "Front Squat", primaryMuscle: "quads", secondaryMuscles: ["core"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "squat_bilateral", contraindications: ["wrist", "knee"], cues: ["Elbows up, stay tall"] },
  { name: "Leg Press", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Full range, don't lock the knees out hard"] },
  { name: "Bulgarian Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell", "bodyweight"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Torso stays tall, back knee drops straight down"] },
  { name: "Walking Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell", "bodyweight"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", cues: ["Step long enough that the front knee stays over the ankle"] },
  { name: "Conventional Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Bar stays close, push the floor away"] },
  { name: "Romanian Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes"], movementPattern: "hinge", equipment: ["barbell", "dumbbell"], loadingType: "external", difficulty: 3, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Hinge at the hips, soft knees, feel the hamstring stretch"] },
  { name: "Kettlebell Swing", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], movementPattern: "hinge", equipment: ["kettlebell"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_ballistic", cues: ["Hips snap, arms are just along for the ride"] },
  { name: "Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_bilateral", cues: ["Chin tucked, drive through the heels"] },
  { name: "Barbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], movementPattern: "h_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Shoulder blades pinched, bar to the sternum"] },
  { name: "Dumbbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], movementPattern: "h_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", cues: ["Control the descent, press up and slightly in"] },
  { name: "Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps", "core"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Body in one line, elbows at 45 degrees"] },
  { name: "Cable Chest Fly", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "chest_isolation", cues: ["Slight bend in the elbow the whole way"] },
  { name: "Barbell Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["Flat back, pull to the belly button"] },
  { name: "Seated Cable Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Chest up, drive elbows back"] },
  { name: "One-Arm Dumbbell Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Flat back, pull elbow toward the hip"] },
  { name: "Pull-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "vertical_pull", cues: ["Chest to the bar, control the way down"] },
  { name: "Lat Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["cable", "machine"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_pull", cues: ["Pull with the elbows, not the hands"] },
  { name: "Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Ribs down, press over the crown of the head"] },
  { name: "Dumbbell Shoulder Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "vertical_press", cues: ["Press up and slightly in, don't flare the elbows"] },
  { name: "Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "shoulder_isolation", cues: ["Lead with the elbows, stop at shoulder height"] },
  { name: "Farmer's Carry", primaryMuscle: "forearms", secondaryMuscles: ["core", "traps"], movementPattern: "carry", equipment: ["dumbbell", "kettlebell"], loadingType: "distance", difficulty: 1, substitutionGroup: "carry", cues: ["Tall posture, don't let the shoulders round"] },
  { name: "Suitcase Carry", primaryMuscle: "core", secondaryMuscles: ["forearms"], movementPattern: "carry", equipment: ["dumbbell", "kettlebell"], isUnilateral: true, loadingType: "distance", difficulty: 2, substitutionGroup: "carry", cues: ["Resist leaning toward the loaded side"] },
  { name: "Pallof Press", primaryMuscle: "core", movementPattern: "anti_rotation", equipment: ["cable", "band"], loadingType: "time", difficulty: 1, substitutionGroup: "anti_rotation", cues: ["Resist the pull, don't let the hips turn"] },
  { name: "Russian Twist", primaryMuscle: "core", movementPattern: "rotation", equipment: ["bodyweight", "dumbbell"], loadingType: "time", difficulty: 1, substitutionGroup: "rotation", cues: ["Rotate from the ribs, not just the arms"] },
  { name: "Plank", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, substitutionGroup: "core_hold", cues: ["Ribs down, glutes squeezed, don't sag"] },
  { name: "Dead Bug", primaryMuscle: "core", movementPattern: "anti_rotation", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, substitutionGroup: "anti_rotation", cues: ["Low back pressed into the floor the whole time"] },
  { name: "Barbell Bicep Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Elbows pinned, no swinging"] },
  { name: "Triceps Pushdown", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "tricep_isolation", cues: ["Elbows stay at your sides"] },
  { name: "Seated Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "calf_isolation", cues: ["Full stretch at the bottom, pause at the top"] },
  { name: "Kettlebell Goblet Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", cues: ["Step back soft, front shin stays vertical"] },
  { name: "Rowing Machine (Erg)", primaryMuscle: "back", secondaryMuscles: ["legs", "core"], movementPattern: "conditioning", equipment: ["machine"], loadingType: "calories", difficulty: 1, cues: ["Legs, then lean, then arms — reverse it coming back"] },
  { name: "Assault Bike", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "calories", difficulty: 1, cues: ["Steady breathing, don't spike the first 10 seconds"] },
  { name: "Kettlebell Goblet March", primaryMuscle: "core", movementPattern: "conditioning", equipment: ["kettlebell", "bodyweight"], loadingType: "time", difficulty: 1, cues: ["Knee to hip height, stay tall"] },
  { name: "Incline Walk", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "time", difficulty: 1, cues: ["Steady pace you could hold a conversation at"] },

  // --- Squat pattern, bilateral (share substitutionGroup with the 4 above) ---
  { name: "Box Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", contraindications: ["lower_back", "knee"], cues: ["Sit back until you touch the box, then stand tall", "Keep the shins mostly vertical"] },
  { name: "Zercher Squat", primaryMuscle: "quads", secondaryMuscles: ["core", "back"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "squat_bilateral", contraindications: ["lower_back"], cues: ["Hold the bar in the crook of your elbows, chest tall", "Brace hard before you descend"] },
  { name: "Hack Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "squat_bilateral", contraindications: ["knee"], cues: ["Feet slightly forward on the platform", "Lower under control, don't bounce at the bottom"] },
  { name: "Smith Machine Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "squat_bilateral", contraindications: ["knee"], cues: ["Feet slightly ahead of the bar", "Push the floor away through the whole foot"] },
  { name: "Dumbbell Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Dumbbells at your sides, chest tall", "Sit down and back like you're reaching for a chair"] },
  { name: "Kettlebell Double Front Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], movementPattern: "squat", equipment: ["kettlebell"], loadingType: "external", difficulty: 2, substitutionGroup: "squat_bilateral", contraindications: ["wrist"], cues: ["Kettlebells racked at the shoulders, elbows tucked", "Keep the torso upright as you descend"] },
  { name: "Bodyweight Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Feet shoulder width, sit the hips back", "Knees track over the toes"] },
  { name: "Wall Sit", primaryMuscle: "quads", movementPattern: "squat", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, substitutionGroup: "squat_bilateral", contraindications: ["knee"], cues: ["Thighs parallel to the floor, back flat on the wall", "Breathe steadily, don't hold your breath"] },
  { name: "Belt Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["machine"], loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", cues: ["Load hangs from the belt, spine stays neutral", "Drive through the whole foot to stand"] },
  { name: "Safety Bar Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", contraindications: ["lower_back", "knee"], cues: ["Handles let the shoulders relax, chest still tall", "Same depth and pace as a normal squat"] },
  { name: "Overhead Squat", primaryMuscle: "quads", secondaryMuscles: ["shoulders", "core"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 5, substitutionGroup: "squat_bilateral", contraindications: ["shoulder", "lower_back", "knee"], cues: ["Bar stays stacked over the middle of the foot", "Only go as deep as you can keep the bar overhead"] },
  { name: "Sumo Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "squat_bilateral", cues: ["Wide stance, toes turned out", "Knees push out in the same direction as the toes"] },
  { name: "Resistance Band Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Band anchored under the feet or overhead, keep tension the whole rep", "Stand up tall at the top"] },
  { name: "Cable Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Cable at chest height pulls you back, that's the counterbalance", "Sit back and keep the heels down"] },
  { name: "Pin Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", contraindications: ["lower_back"], cues: ["Pause dead still on the pins, then drive up with no bounce", "Reset your brace at the bottom"] },
  { name: "Landmine Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "squat_bilateral", cues: ["Hold the sleeve at chest height with both hands", "Sit back and keep the bar path straight"] },
  { name: "Single-Leg Leg Press", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["machine"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "squat_bilateral", contraindications: ["knee"], cues: ["Full foot on the platform, control the negative", "Don't let the knee cave in"] },
  { name: "Squat to Box", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "squat_bilateral", contraindications: ["knee"], cues: ["Lightly tap the box and stand back up", "Keep the chest up the whole way down"] },
  { name: "Dumbbell Box Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Sit back to lightly touch the box", "Stand tall without using momentum"] },
  { name: "Banded Bodyweight Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "squat", equipment: ["band"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "squat_bilateral", cues: ["Band around the thighs adds a bit of resistance", "Push the knees out against the band as you stand"] },

  // --- Lunge / unilateral squat pattern ---
  { name: "Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Step back soft, drop the back knee straight down", "Push through the front heel to return"] },
  { name: "Forward Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Step out and land soft on the front foot", "Push back to the start rather than walking through"] },
  { name: "Lateral Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Sit back into the hip on the stepping side", "Other leg stays straight, foot flat"] },
  { name: "Curtsy Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Step the back foot behind and across", "Keep the hips square to the front"] },
  { name: "Step-Up", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Drive through the whole foot on the box, don't push off the back toe", "Stand fully tall at the top"] },
  { name: "Lateral Step-Up", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Step sideways onto the box, drive up through that leg", "Lower back down under control"] },
  { name: "Single-Leg Box Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Reach the hips back and lightly tap the box", "Keep the working knee tracking over the foot"] },
  { name: "Skater Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 4, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Reach the back leg behind you as you sit down", "Touch down light and stand back up in control"] },
  { name: "Cossack Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Shift your weight fully to one side", "Keep the loaded heel down as long as you can"] },
  { name: "Deficit Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Standing on a small step increases the range, control it", "Step back and touch the heel down light"] },
  { name: "Barbell Walking Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee", "lower_back"], cues: ["Bar stays level across the shoulders", "Take a stride length you can control, not your longest step"] },
  { name: "Barbell Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee", "lower_back"], cues: ["Step back under control, front shin stays vertical", "Drive up through the front leg"] },
  { name: "Kettlebell Front Rack Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Kettlebell racked at the shoulder, elbow tucked", "Step back soft and return to standing"] },
  { name: "Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Feet set in a long stride, back heel lifted", "Drop straight down, drive straight up"] },
  { name: "Smith Machine Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["machine"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Back foot elevated slightly if that's comfortable", "Front knee tracks over the foot"] },
  { name: "Pistol Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], movementPattern: "lunge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 5, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Reach the free leg out in front for balance", "Go only as low as you can control"] },
  { name: "Assisted Pistol Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["band"], isUnilateral: true, loadingType: "bodyweight", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Band takes some of your weight at the bottom", "Focus on a smooth, controlled descent"] },
  { name: "Step Down", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Lower the free foot to lightly tap the floor", "Control the descent, don't drop"] },
  { name: "Dumbbell Lateral Step-Down", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Step down and out to the side under control", "Keep the standing knee tracking over the foot"] },
  { name: "Kettlebell Bulgarian Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Rear foot up on the bench, torso stays tall", "Front knee tracks over the foot, not past the toes"] },
  { name: "Walking Lunge with Overhead Reach", primaryMuscle: "quads", secondaryMuscles: ["glutes", "shoulders"], movementPattern: "lunge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee", "shoulder"], cues: ["Reach the dumbbells overhead as you step", "Keep the ribs down, don't overarch the back"] },
  { name: "Landmine Reverse Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Hold the sleeve at the chest, step back soft", "Front shin stays vertical through the rep"] },
  { name: "Kettlebell Racked Walking Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes"], movementPattern: "lunge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "lunge", contraindications: ["knee"], cues: ["Kettlebells racked at the shoulders as you step", "Keep the torso tall through every step"] },

  // --- Hinge pattern, bilateral ---
  { name: "Sumo Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back", "pregnancy"], cues: ["Wide stance, grip inside the knees", "Chest up, drive the floor away with the legs"] },
  { name: "Trap Bar Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "quads"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Stand tall inside the frame before you pull", "Push the floor away, keep the bar close"] },
  { name: "Good Morning", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Soft knees, hinge from the hips", "Keep the bar path directly over mid-foot"] },
  { name: "Seated Good Morning", primaryMuscle: "hamstrings", secondaryMuscles: ["back"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Sitting removes leg drive, isolates the hinge", "Hinge from the hips, chest stays up"] },
  { name: "Cable Pull-Through", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes"], movementPattern: "hinge", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Hinge back until you feel the hamstring stretch", "Squeeze the glutes to stand tall"] },
  { name: "Kettlebell Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes"], movementPattern: "hinge", equipment: ["kettlebell"], loadingType: "external", difficulty: 1, substitutionGroup: "hinge_bilateral", cues: ["Kettlebell between the feet, hinge and grip it", "Stand tall by pushing the floor away"] },
  { name: "Glute Bridge", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "hinge_bilateral", cues: ["Feet flat, drive the hips up", "Squeeze at the top for a full second"] },
  { name: "Back Extension", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["machine"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Hinge at the hips, not the lower back", "Come up to a flat line, don't overextend"] },
  { name: "Nordic Hamstring Curl", primaryMuscle: "hamstrings", movementPattern: "hinge", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 5, substitutionGroup: "hinge_bilateral", contraindications: ["knee"], cues: ["Lower yourself as slowly as you can control", "Catch yourself with your hands if you need to"] },
  { name: "Band Good Morning", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["band"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Band anchored low or under the feet", "Hinge at the hips, chest stays up"] },
  { name: "Dumbbell Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "back"], movementPattern: "hinge", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "hinge_bilateral", cues: ["Dumbbells close to the shins", "Push the floor away, keep the back flat"] },
  { name: "Rack Pull", primaryMuscle: "hamstrings", secondaryMuscles: ["back", "glutes"], movementPattern: "hinge", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "hinge_bilateral", contraindications: ["lower_back"], cues: ["Bar starts above the knee", "Stand tall by driving the hips forward"] },
  { name: "Machine Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_bilateral", cues: ["Upper back braced against the pad", "Drive the hips up and squeeze"] },
  { name: "Banded Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "hinge_bilateral", cues: ["Band across the hips for extra resistance at the top", "Drive through the heels"] },
  { name: "Kettlebell Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["kettlebell"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_bilateral", cues: ["Kettlebell resting across the hips", "Squeeze the glutes hard at the top"] },

  // --- Hinge pattern, unilateral ---
  { name: "Single-Leg Romanian Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Hinge forward as the back leg lifts behind you", "Keep the hips square to the floor"] },
  { name: "Single-Leg Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Reach the kettlebell toward the floor as one leg lifts", "Keep a soft bend in the standing knee"] },
  { name: "Single-Leg Glute Bridge", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 2, substitutionGroup: "hinge_unilateral", cues: ["One foot planted, drive the hips up evenly", "Don't let the hips tilt to one side"] },
  { name: "Bodyweight Single-Leg RDL", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 2, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Reach forward as the back leg extends behind you", "Keep the hips level throughout"] },
  { name: "Cable Single-Leg RDL", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Cable pulls you forward as a light counterbalance", "Hinge from the hip, not the lower back"] },
  { name: "Suitcase Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["core", "forearms"], movementPattern: "hinge", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["One dumbbell at your side, resist leaning", "Push the floor away evenly through both feet"] },
  { name: "Landmine Single-Leg RDL", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Hold the sleeve with one hand as a counterbalance", "Hinge slow and controlled"] },
  { name: "Single-Arm Kettlebell Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], movementPattern: "hinge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "hinge_unilateral", contraindications: ["lower_back"], cues: ["Kettlebell in one hand, hips square to the floor", "Push the floor away to stand"] },
  { name: "Single-Leg Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], movementPattern: "hinge", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 3, substitutionGroup: "hinge_unilateral", cues: ["Shoulders on the bench, one foot planted", "Drive up without letting the hips tilt"] },

  // --- Hinge pattern, ballistic ---
  { name: "Kettlebell Single-Arm Clean", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "forearms"], movementPattern: "hinge", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 4, substitutionGroup: "hinge_ballistic", contraindications: ["wrist", "shoulder"], cues: ["Keep the kettlebell close as it comes up", "Let the wrist rotate at the top, don't muscle it"] },
  { name: "Dumbbell Swing", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], movementPattern: "hinge", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "hinge_ballistic", cues: ["Same hip-snap pattern as a kettlebell swing", "Arms stay relaxed, hips do the work"] },
  { name: "Kettlebell Alternating Swing", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], movementPattern: "hinge", equipment: ["kettlebell"], loadingType: "external", difficulty: 3, substitutionGroup: "hinge_ballistic", cues: ["Pass the bell between hands at the top of the snap", "Keep the hips driving the movement, not the arms"] },

  // --- Horizontal push (chest) ---
  { name: "Incline Barbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["shoulders", "triceps"], movementPattern: "h_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Bar comes down to the upper chest", "Keep the shoulder blades pulled together"] },
  { name: "Incline Dumbbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["shoulders", "triceps"], movementPattern: "h_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Press up and slightly back", "Control the dumbbells down to chest level"] },
  { name: "Decline Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Bar path angles slightly down toward the lower chest", "Keep the feet locked under the pads"] },
  { name: "Close-Grip Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder", "wrist"], cues: ["Hands just inside shoulder width", "Elbows stay closer to the body on the way down"] },
  { name: "Machine Chest Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Handles at chest height, press straight out", "Control the return, don't let the weight stack slam"] },
  { name: "Smith Machine Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Same bar path as a free bench press", "Unrack and rerack with control"] },
  { name: "Floor Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Upper arms rest lightly on the floor at the bottom", "Press straight up, pause briefly at the floor each rep"] },
  { name: "Single-Arm Dumbbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "core"], movementPattern: "h_push", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Brace the core hard to stop the torso from rotating", "Press straight up over the shoulder"] },
  { name: "Push-Up on Knees", primaryMuscle: "chest", secondaryMuscles: ["triceps", "core"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Straight line from knees to head", "Lower with control, don't let the hips sag"] },
  { name: "Incline Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Hands on a bench or box, easier than a floor push-up", "Body stays in one straight line"] },
  { name: "Decline Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 3, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Feet elevated on a bench or box", "Keep the core braced so the hips don't sag"] },
  { name: "Band Chest Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Band anchored behind you at chest height", "Press forward and control the return"] },
  { name: "Cable Chest Press", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", cues: ["Cables at chest height, step forward into a slight lean", "Press forward and squeeze at full extension"] },
  { name: "Dip", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Lower until you feel a stretch in the front of the shoulder, no further", "Keep a slight forward lean to protect the shoulders"] },
  { name: "Weighted Dip", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bw_plus_load", difficulty: 5, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Same range as a bodyweight dip, added load hangs from a belt", "Control the descent, don't drop into the bottom"] },
  { name: "Machine Dip", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_press", contraindications: ["shoulder"], cues: ["Press down and slightly forward", "Stop before the shoulders round forward"] },
  { name: "Bench Dip", primaryMuscle: "triceps", secondaryMuscles: ["chest", "shoulders"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "horizontal_press", contraindications: ["shoulder", "wrist"], cues: ["Hands on the bench behind you, hips close to the edge", "Lower only as far as feels comfortable in the shoulders"] },
  { name: "Resistance Band Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps", "core"], movementPattern: "h_push", equipment: ["band", "bodyweight"], loadingType: "bw_plus_load", difficulty: 2, substitutionGroup: "horizontal_press", cues: ["Band across the upper back adds resistance at the top", "Body stays in one straight line"] },
  { name: "Wide Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps"], movementPattern: "h_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "horizontal_press", cues: ["Hands set wider than shoulder width", "Keep the elbows from flaring straight out to the sides"] },

  // --- Chest isolation ---
  { name: "Dumbbell Chest Fly", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "chest_isolation", contraindications: ["shoulder"], cues: ["Slight bend in the elbows the whole way", "Bring the dumbbells together like hugging a big barrel"] },
  { name: "Pec Deck Machine", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "chest_isolation", cues: ["Pads or handles at chest height", "Squeeze the chest at the finish, don't slam the weight back"] },
  { name: "Incline Cable Fly", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "chest_isolation", contraindications: ["shoulder"], cues: ["Cables set low, pull up and across", "Finish with the hands in front of the upper chest"] },
  { name: "Low-to-High Cable Fly", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "chest_isolation", cues: ["Cables set low, sweep up and in", "Keep a soft bend in the elbows throughout"] },
  { name: "Band Chest Fly", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "chest_isolation", cues: ["Band anchored behind you", "Bring the hands together in front of the chest"] },
  { name: "Dumbbell Squeeze Press", primaryMuscle: "chest", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "chest_isolation", cues: ["Press the dumbbells together hard the whole set", "Push up and slightly forward"] },

  // --- Horizontal pull (back) ---
  { name: "Chest-Supported Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Chest rests on the bench, no need to brace the lower back", "Pull the elbows back and squeeze"] },
  { name: "T-Bar Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["Hinge and keep a flat back", "Pull the handle to the lower chest"] },
  { name: "Pendlay Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["Bar starts on the floor each rep", "Pull with purpose, chest toward the bar"] },
  { name: "Machine Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Chest against the pad if there is one", "Pull the elbows back, squeeze the shoulder blades"] },
  { name: "Inverted Row", primaryMuscle: "back", secondaryMuscles: ["biceps", "core"], movementPattern: "h_pull", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Body in a straight line, pull the chest to the bar", "Lower under control"] },
  { name: "Band Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Band anchored in front at chest height", "Pull the elbows back and squeeze"] },
  { name: "Meadows Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["One end of the bar anchored in a landmine or corner", "Pull with the elbow, not the hand"] },
  { name: "Single-Arm Cable Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Pull the elbow straight back", "Keep the chest tall, don't lean back to pull"] },
  { name: "Renegade Row", primaryMuscle: "back", secondaryMuscles: ["core", "biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 4, substitutionGroup: "horizontal_pull", contraindications: ["shoulder", "wrist"], cues: ["Feet wide for a stable base in the plank", "Row one dumbbell without letting the hips rotate"] },
  { name: "Kettlebell Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Flat back, pull the elbow to the hip", "Keep the hips square to the floor"] },
  { name: "Machine Chest-Supported Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Chest against the pad, pull the handles back", "Squeeze the shoulder blades together at the end"] },
  { name: "Cable Face-Away Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Stand facing away from the stack", "Pull the elbows back and slightly down"] },
  { name: "Dumbbell Bent-Over Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["Flat back, hinge to about 45 degrees", "Pull both dumbbells to the ribs together"] },
  { name: "Landmine Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["Straddle the bar, hinge forward", "Pull the sleeve up to the chest"] },
  { name: "Barbell Yates Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "horizontal_pull", contraindications: ["lower_back"], cues: ["A slightly more upright torso than a standard barbell row", "Pull to the hips, elbows driving back"] },
  { name: "Seal Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Lying face down on a raised bench takes the lower back out of it", "Pull the elbows back and squeeze"] },
  { name: "Dumbbell Incline Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "horizontal_pull", cues: ["Chest supported on an incline bench", "Pull both dumbbells up and squeeze"] },
  { name: "Cable Standing Rope Row", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "h_pull", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "horizontal_pull", cues: ["Rope attachment, pull to the ribs", "Keep the elbows close to the body"] },

  // --- Vertical pull (back) ---
  { name: "Chin-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "vertical_pull", cues: ["Palms facing you, chest to the bar", "Lower all the way down under control"] },
  { name: "Neutral-Grip Pull-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "vertical_pull", cues: ["Palms facing each other on the handles", "Pull the chest toward the bar, not just the chin"] },
  { name: "Assisted Pull-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["machine"], loadingType: "bw_plus_load", difficulty: 2, substitutionGroup: "vertical_pull", cues: ["The counterweight supports part of your bodyweight", "Focus on pulling with the back, not just the arms"] },
  { name: "Band-Assisted Pull-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["band"], loadingType: "bw_plus_load", difficulty: 3, substitutionGroup: "vertical_pull", cues: ["Band under one or both feet takes some of the load", "Full range, chest to the bar"] },
  { name: "Wide-Grip Lat Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "vertical_pull", cues: ["Hands wider than shoulder width", "Pull to the upper chest, lead with the elbows"] },
  { name: "Close-Grip Lat Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_pull", cues: ["Narrow or neutral grip attachment", "Pull the elbows down and back"] },
  { name: "Single-Arm Lat Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "vertical_pull", cues: ["Pull the elbow down toward the hip", "Keep the torso still, no leaning back"] },
  { name: "Kneeling Band Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_pull", cues: ["Band anchored high overhead", "Pull the elbows down to the ribs"] },
  { name: "Machine Assisted Pull-Up", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["machine"], loadingType: "bw_plus_load", difficulty: 2, substitutionGroup: "vertical_pull", cues: ["Set the assistance so the last rep is still hard", "Pull the chest up toward the handles"] },
  { name: "Reverse-Grip Lat Pulldown", primaryMuscle: "back", secondaryMuscles: ["biceps"], movementPattern: "v_pull", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_pull", cues: ["Palms face you on the bar", "Pull down to the upper chest, squeeze at the bottom"] },

  // --- Back isolation ---
  { name: "Straight-Arm Pulldown", primaryMuscle: "back", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "back_isolation", cues: ["Arms stay almost straight the whole rep", "Pull down with the lats, not the arms"] },
  { name: "Dumbbell Pullover", primaryMuscle: "back", secondaryMuscles: ["chest"], movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "back_isolation", contraindications: ["shoulder"], cues: ["Lower the dumbbell behind the head with a slight elbow bend", "Pull back over the chest using the lats"] },
  { name: "Cable Pullover", primaryMuscle: "back", secondaryMuscles: ["chest"], movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "back_isolation", cues: ["Cable set high, arms nearly straight", "Pull down and back using the lats, not the arms"] },
  { name: "Machine Pullover", primaryMuscle: "back", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "back_isolation", cues: ["Elbows rest on the pads", "Pull down and back, focus on the squeeze"] },

  // --- Vertical push (shoulders) ---
  { name: "Push Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "quads"], movementPattern: "v_push", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "vertical_press", contraindications: ["shoulder", "lower_back"], cues: ["A small dip and drive with the legs starts the bar moving", "Lock out overhead, don't lean back to finish"] },
  { name: "Seated Barbell Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Back supported, press straight up", "Keep the ribs down through the top of the rep"] },
  { name: "Seated Dumbbell Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Back supported against the bench", "Press up without arching the lower back"] },
  { name: "Arnold Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["dumbbell"], loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Rotate the palms as you press up", "Finish with the palms facing forward overhead"] },
  { name: "Machine Shoulder Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_press", cues: ["Handles start at shoulder height", "Press straight up, control the way down"] },
  { name: "Landmine Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["barbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "vertical_press", cues: ["Sleeve starts at the shoulder", "Press up and slightly forward along the natural arc"] },
  { name: "Single-Arm Dumbbell Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], movementPattern: "v_push", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Brace the core so the torso doesn't lean", "Press straight up over the shoulder"] },
  { name: "Kettlebell Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["kettlebell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder", "wrist"], cues: ["Kettlebell racked at the shoulder to start", "Press up and slightly back, stack it over the shoulder"] },
  { name: "Pike Push-Up", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder", "wrist"], cues: ["Hips high, roughly an upside-down V shape", "Lower the head toward the floor between the hands"] },
  { name: "Handstand Push-Up", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 5, substitutionGroup: "vertical_press", contraindications: ["shoulder", "wrist"], cues: ["Feet against the wall for support", "Only go as deep as you can press back out of safely"] },
  { name: "Band Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "vertical_press", cues: ["Band anchored under the feet", "Press straight overhead, keep the ribs down"] },
  { name: "Cable Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], movementPattern: "v_push", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "vertical_press", cues: ["Cable set low, press straight overhead", "Keep a steady, even tempo"] },
  { name: "Half-Kneeling Dumbbell Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], movementPattern: "v_push", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 3, substitutionGroup: "vertical_press", contraindications: ["shoulder"], cues: ["Half-kneeling position builds a stable base", "Press straight up without leaning back"] },
  { name: "Z Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], movementPattern: "v_push", equipment: ["barbell"], loadingType: "external", difficulty: 4, substitutionGroup: "vertical_press", contraindications: ["shoulder", "lower_back"], cues: ["Sitting on the floor removes any leg drive", "Press straight up while staying tall through the spine"] },

  // --- Shoulder isolation: lateral, rear delt, front, upright row, traps, rotator cuff ---
  { name: "Cable Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "shoulder_isolation", cues: ["Lead with the elbow, not the hand", "Stop at shoulder height"] },
  { name: "Band Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "shoulder_isolation", cues: ["Step on the band for the right tension", "Raise to shoulder height, no higher"] },
  { name: "Machine Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "shoulder_isolation", cues: ["Pads sit against the outside of the upper arms", "Raise with control, don't use momentum"] },
  { name: "Leaning Cable Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "shoulder_isolation", cues: ["Lean away slightly from the cable for a longer range", "Raise the arm out to the side, lead with the elbow"] },
  { name: "Dumbbell Cross-Body Lateral Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "shoulder_isolation", cues: ["Raise the dumbbell across in front of the body", "Keep the movement slow and controlled"] },
  { name: "Dumbbell Rear Delt Fly", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "rear_delt_isolation", cues: ["Hinge forward, slight bend in the elbows", "Raise the arms out to the sides, squeeze the shoulder blades"] },
  { name: "Cable Rear Delt Fly", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "rear_delt_isolation", cues: ["Cross the cables in front of you to start", "Pull out and back, squeeze the shoulder blades"] },
  { name: "Machine Rear Delt Fly", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "rear_delt_isolation", cues: ["Chest against the pad if there is one", "Pull the handles back and out"] },
  { name: "Face Pull", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "rear_delt_isolation", cues: ["Pull toward the face, elbows high", "Finish with the thumbs pointing back"] },
  { name: "Band Face Pull", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "rear_delt_isolation", cues: ["Band anchored at face height", "Pull apart and back, elbows stay high"] },
  { name: "Band Pull-Apart", primaryMuscle: "shoulders", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "rear_delt_isolation", cues: ["Arms straight out in front at chest height", "Pull the band apart and squeeze the shoulder blades"] },
  { name: "Dumbbell Front Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "front_raise", cues: ["Raise to about shoulder height, no higher", "Lower with control, don't swing"] },
  { name: "Cable Front Raise", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "front_raise", cues: ["Cable between the legs or from a low anchor", "Raise straight in front to shoulder height"] },
  { name: "Barbell Upright Row", primaryMuscle: "shoulders", secondaryMuscles: ["traps"], movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "upright_row", contraindications: ["shoulder"], cues: ["Pull the bar up close to the body", "Stop around chest height, elbows leading"] },
  { name: "Cable Upright Row", primaryMuscle: "shoulders", secondaryMuscles: ["traps"], movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "upright_row", contraindications: ["shoulder"], cues: ["Pull straight up along the body", "Lead with the elbows, not the hands"] },
  { name: "Barbell Shrug", primaryMuscle: "traps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 1, substitutionGroup: "traps_isolation", cues: ["Lift the shoulders straight up toward the ears", "No need to roll the shoulders, just up and down"] },
  { name: "Dumbbell Shrug", primaryMuscle: "traps", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "traps_isolation", cues: ["Lift straight up, pause briefly at the top", "Lower under control"] },
  { name: "Cable Shrug", primaryMuscle: "traps", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "traps_isolation", cues: ["Same straight-up motion as a dumbbell shrug", "Keep the arms relaxed, let the traps do the work"] },
  { name: "Trap Bar Shrug", primaryMuscle: "traps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 1, substitutionGroup: "traps_isolation", cues: ["Stand tall inside the frame", "Shrug straight up and pause briefly at the top"] },
  { name: "Band External Rotation", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "rotator_cuff", cues: ["Elbow pinned to your side at 90 degrees", "Rotate the forearm out slowly, no swinging"] },
  { name: "Cable Internal Rotation", primaryMuscle: "shoulders", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "rotator_cuff", cues: ["Elbow pinned to your side at 90 degrees", "Rotate the forearm in slowly and with control"] },

  // --- Carry ---
  { name: "Front Rack Carry", primaryMuscle: "core", secondaryMuscles: ["shoulders", "forearms"], movementPattern: "carry", equipment: ["kettlebell"], loadingType: "distance", difficulty: 2, substitutionGroup: "carry", contraindications: ["wrist"], cues: ["Kettlebells racked at the shoulders, elbows tucked", "Walk with short, controlled steps"] },
  { name: "Overhead Carry", primaryMuscle: "core", secondaryMuscles: ["shoulders"], movementPattern: "carry", equipment: ["dumbbell"], loadingType: "distance", difficulty: 3, substitutionGroup: "carry", contraindications: ["shoulder"], cues: ["Arms locked out straight overhead", "Ribs down, don't let them flare out"] },
  { name: "Waiter's Carry", primaryMuscle: "core", secondaryMuscles: ["shoulders"], movementPattern: "carry", equipment: ["kettlebell"], isUnilateral: true, loadingType: "distance", difficulty: 2, substitutionGroup: "carry", contraindications: ["shoulder"], cues: ["Kettlebell balanced overhead on an open palm", "Walk slow and controlled, eyes forward"] },
  { name: "Trap Bar Farmer's Carry", primaryMuscle: "forearms", secondaryMuscles: ["core", "traps"], movementPattern: "carry", equipment: ["barbell"], loadingType: "distance", difficulty: 2, substitutionGroup: "carry", cues: ["Stand tall inside the frame before you walk", "Don't let the shoulders round forward"] },
  { name: "Cross-Body Carry", primaryMuscle: "core", secondaryMuscles: ["shoulders", "forearms"], movementPattern: "carry", equipment: ["kettlebell"], isUnilateral: true, loadingType: "distance", difficulty: 2, substitutionGroup: "carry", cues: ["Kettlebell held at the opposite shoulder, front rack style", "Keep the torso upright, resist twisting"] },
  { name: "Zercher Carry", primaryMuscle: "core", secondaryMuscles: ["back", "forearms"], movementPattern: "carry", equipment: ["barbell"], loadingType: "distance", difficulty: 3, substitutionGroup: "carry", contraindications: ["lower_back"], cues: ["Bar cradled in the elbows, chest tall", "Walk with short controlled steps"] },

  // --- Rotation ---
  { name: "Cable Woodchop", primaryMuscle: "core", movementPattern: "rotation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "rotation", contraindications: ["lower_back"], cues: ["Rotate from the ribs and hips together", "Keep the arms relatively straight, let the torso do the work"] },
  { name: "Standing Cable Rotation", primaryMuscle: "core", movementPattern: "rotation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "rotation", cues: ["Start and finish facing forward", "Rotate through the torso, not just the arms"] },
  { name: "Band Rotation", primaryMuscle: "core", movementPattern: "rotation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "rotation", cues: ["Band anchored to the side at chest height", "Rotate away from the anchor with control"] },
  { name: "Landmine Rotation", primaryMuscle: "core", movementPattern: "rotation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "rotation", contraindications: ["lower_back"], cues: ["Hold the sleeve with both hands, arms extended", "Rotate the bar side to side using the torso"] },

  // --- Anti-rotation ---
  { name: "Half-Kneeling Pallof Press", primaryMuscle: "core", movementPattern: "anti_rotation", equipment: ["cable"], isUnilateral: true, loadingType: "time", difficulty: 2, substitutionGroup: "anti_rotation", cues: ["Half-kneeling position takes the legs out of it", "Press straight out and resist the pull to rotate"] },
  { name: "Band Anti-Rotation Hold", primaryMuscle: "core", movementPattern: "anti_rotation", equipment: ["band"], loadingType: "time", difficulty: 1, substitutionGroup: "anti_rotation", cues: ["Press the band straight out and hold", "Resist any twist in the hips or shoulders"] },
  { name: "Bird Dog", primaryMuscle: "core", secondaryMuscles: ["glutes", "back"], movementPattern: "anti_rotation", equipment: ["bodyweight"], isUnilateral: true, loadingType: "time", difficulty: 1, substitutionGroup: "anti_rotation", cues: ["Opposite arm and leg extend together", "Keep the hips level, don't let the low back sag"] },

  // --- Core holds ---
  { name: "Side Plank", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], isUnilateral: true, loadingType: "time", difficulty: 2, substitutionGroup: "core_hold", cues: ["Stack the hips, body in one straight line", "Don't let the top hip roll forward"] },
  { name: "Hollow Body Hold", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "time", difficulty: 3, substitutionGroup: "core_hold", contraindications: ["lower_back"], cues: ["Low back pressed into the floor", "Arms and legs extended only as far as you can hold the position"] },
  { name: "Forearm Plank with Shoulder Taps", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "time", difficulty: 2, substitutionGroup: "core_hold", cues: ["Feet a little wider for stability", "Tap the opposite shoulder without letting the hips rock"] },
  { name: "Weighted Plank", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bw_plus_load", difficulty: 3, substitutionGroup: "core_hold", contraindications: ["lower_back", "wrist"], cues: ["A light plate on the upper back adds load", "Keep the same straight line as a regular plank"] },

  // --- Core flexion ---
  { name: "Hanging Knee Raise", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 3, substitutionGroup: "core_flexion", contraindications: ["shoulder"], cues: ["Hang tall, curl the knees up toward the chest", "Lower with control, don't swing"] },
  { name: "Hanging Leg Raise", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "core_flexion", contraindications: ["shoulder", "lower_back"], cues: ["Legs stay straight, raise to hip height or above", "Control the descent, no swinging"] },
  { name: "Cable Crunch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "core_flexion", contraindications: ["lower_back"], cues: ["Kneel below the cable, curl the ribs toward the hips", "Keep the hips still, this is a spine curl not a hip hinge"] },
  { name: "Machine Crunch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "core_flexion", cues: ["Curl forward against the pad", "Exhale as you curl, keep the motion slow"] },
  { name: "Reverse Crunch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "core_flexion", contraindications: ["lower_back"], cues: ["Curl the hips up toward the ribs", "Lower the legs with control, don't let them drop"] },
  { name: "Weighted Sit-Up", primaryMuscle: "core", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "bw_plus_load", difficulty: 2, substitutionGroup: "core_flexion", contraindications: ["lower_back", "pregnancy"], cues: ["Hold the weight at the chest", "Curl up through the spine one segment at a time"] },
  { name: "Bicycle Crunch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "time", difficulty: 2, substitutionGroup: "core_flexion", contraindications: ["lower_back"], cues: ["Slow and controlled, not a race", "Bring elbow to opposite knee without pulling on the neck"] },
  { name: "V-Up", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 3, substitutionGroup: "core_flexion", contraindications: ["lower_back"], cues: ["Reach the hands toward the feet as both lift", "Lower with control instead of dropping"] },
  { name: "Toe Touch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "core_flexion", cues: ["Reach straight up toward the feet, knees soft", "Curl the shoulders off the floor, not the whole back"] },
  { name: "Cable Standing Crunch", primaryMuscle: "core", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "core_flexion", contraindications: ["lower_back"], cues: ["Rope held at the forehead, hips stay still", "Curl the ribs down toward the hips"] },

  // --- Bicep isolation ---
  { name: "Dumbbell Bicep Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Elbows pinned to your sides", "Curl up without swinging the shoulders"] },
  { name: "Hammer Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Palms face each other the whole rep", "Elbows stay still at your sides"] },
  { name: "Incline Dumbbell Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "bicep_isolation", cues: ["Arms hang straight down from a slight incline bench", "Curl up without letting the elbows drift forward"] },
  { name: "Cable Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Elbows pinned to your sides", "Curl up slow, lower even slower"] },
  { name: "Preacher Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "bicep_isolation", contraindications: ["wrist"], cues: ["Upper arms rest fully on the pad", "Don't lock the elbows out hard at the bottom"] },
  { name: "EZ-Bar Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Angled grip is easier on the wrists than a straight bar", "Elbows stay at your sides through the curl"] },
  { name: "Band Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Stand on the band, elbows pinned to the sides", "Curl up under control"] },
  { name: "Concentration Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Elbow braced against the inside of the knee", "Curl up slow, focus on the squeeze at the top"] },
  { name: "Cable Rope Hammer Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Rope attachment, palms face each other", "Elbows stay pinned to your sides"] },
  { name: "Zottman Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "bicep_isolation", cues: ["Curl up with palms facing you", "Rotate the palms down before lowering slowly"] },
  { name: "Drag Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "bicep_isolation", cues: ["Keep the bar dragging up close along the body", "Elbows drift back rather than forward"] },
  { name: "Machine Preacher Curl", primaryMuscle: "biceps", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "bicep_isolation", cues: ["Upper arms locked against the pad", "Curl up slow, lower even slower"] },
  { name: "Reverse Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "bicep_isolation", contraindications: ["wrist"], cues: ["Palms face down the whole rep", "Elbows stay at your sides"] },

  // --- Tricep isolation ---
  { name: "Overhead Triceps Extension", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "tricep_isolation", contraindications: ["shoulder"], cues: ["Elbows point forward, close to the head", "Lower behind the head under control"] },
  { name: "Skull Crusher", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 3, substitutionGroup: "tricep_isolation", contraindications: ["shoulder", "wrist"], cues: ["Elbows stay pointed at the ceiling", "Lower the bar toward the forehead, not past it"] },
  { name: "Cable Overhead Extension", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["cable"], loadingType: "external", difficulty: 2, substitutionGroup: "tricep_isolation", contraindications: ["shoulder"], cues: ["Face away from the stack, elbows high", "Extend the arms without flaring the elbows out"] },
  { name: "Dumbbell Kickback", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["dumbbell"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "tricep_isolation", cues: ["Upper arm stays parallel to the floor", "Extend the forearm back, don't swing it"] },
  { name: "Band Pushdown", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "tricep_isolation", cues: ["Band anchored high", "Elbows stay at your sides through the push"] },
  { name: "Machine Triceps Extension", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "tricep_isolation", cues: ["Upper arms stay against the pads", "Push down until the arms are straight, no locking out hard"] },
  { name: "Close-Grip Push-Up", primaryMuscle: "triceps", secondaryMuscles: ["chest"], movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "tricep_isolation", contraindications: ["wrist"], cues: ["Hands closer than shoulder width", "Elbows track back along the ribs, not out to the sides"] },
  { name: "Tate Press", primaryMuscle: "triceps", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 2, substitutionGroup: "tricep_isolation", contraindications: ["shoulder", "wrist"], cues: ["Elbows point out to the sides, dumbbells meet over the chest", "Lower with control, keep the wrists steady"] },

  // --- Calf isolation ---
  { name: "Standing Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "calf_isolation", cues: ["Full stretch at the bottom", "Rise as high onto the toes as you can"] },
  { name: "Dumbbell Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "calf_isolation", cues: ["Hold the dumbbells at your sides", "Pause briefly at the top of each rep"] },
  { name: "Donkey Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 2, substitutionGroup: "calf_isolation", cues: ["Hinge slightly forward at the hips", "Full range, stretch at the bottom, rise all the way up"] },
  { name: "Single-Leg Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["bodyweight"], isUnilateral: true, loadingType: "bodyweight", difficulty: 2, substitutionGroup: "calf_isolation", cues: ["Hold something light for balance if needed", "Rise all the way up on one foot"] },
  { name: "Leg Press Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "calf_isolation", cues: ["Press through the balls of the feet only", "Let the ankles fully stretch at the bottom"] },
  { name: "Barbell Standing Calf Raise", primaryMuscle: "calves", movementPattern: "isolation", equipment: ["barbell"], loadingType: "external", difficulty: 2, substitutionGroup: "calf_isolation", cues: ["Bar across the upper back like a squat", "Rise onto the toes, then lower with a full stretch"] },

  // --- Quad isolation ---
  { name: "Leg Extension", primaryMuscle: "quads", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "quad_isolation", contraindications: ["knee"], cues: ["Pad rests just above the ankles", "Extend fully but don't slam the weight at the top"] },
  { name: "Sissy Squat", primaryMuscle: "quads", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "quad_isolation", contraindications: ["knee"], cues: ["Lean back as the knees travel forward", "Hold something stable if balance is hard at first"] },
  { name: "Wall Sit with Leg Extension", primaryMuscle: "quads", movementPattern: "isolation", equipment: ["bodyweight"], isUnilateral: true, loadingType: "time", difficulty: 3, substitutionGroup: "quad_isolation", contraindications: ["knee"], cues: ["Hold the wall sit position steady", "Extend one leg out straight and hold"] },
  { name: "Machine Single-Leg Extension", primaryMuscle: "quads", movementPattern: "isolation", equipment: ["machine"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "quad_isolation", contraindications: ["knee"], cues: ["One leg at a time for a bigger focus per side", "Control the weight back down, don't drop it"] },

  // --- Hamstring isolation ---
  { name: "Lying Leg Curl", primaryMuscle: "hamstrings", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "hamstring_isolation", cues: ["Hips stay pressed into the pad", "Curl the heels toward the glutes, then lower slow"] },
  { name: "Seated Leg Curl", primaryMuscle: "hamstrings", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "hamstring_isolation", cues: ["Back against the pad, thighs secured", "Curl down and squeeze at the bottom"] },
  { name: "Cable Leg Curl", primaryMuscle: "hamstrings", movementPattern: "isolation", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 2, substitutionGroup: "hamstring_isolation", cues: ["Ankle cuff attached to the cable", "Curl the heel toward the glute, control the return"] },
  { name: "Glute-Ham Raise", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes"], movementPattern: "isolation", equipment: ["machine"], loadingType: "bodyweight", difficulty: 4, substitutionGroup: "hamstring_isolation", contraindications: ["knee"], cues: ["Lower yourself with control from the knees", "Use the hamstrings to pull back up"] },
  { name: "Stability Leg Curl", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes"], movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 2, substitutionGroup: "hamstring_isolation", cues: ["Heels dig in, hips lifted off the floor", "Curl the heels toward the glutes while keeping the hips up"] },

  // --- Glute isolation, hip abductor, hip adductor ---
  { name: "Cable Glute Kickback", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "glute_isolation", cues: ["Small controlled range, don't overarch the low back", "Squeeze the glute at the top of the movement"] },
  { name: "Frog Pump", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "bodyweight", difficulty: 1, substitutionGroup: "glute_isolation", cues: ["Soles of the feet together, knees out wide", "Drive the hips up and squeeze the glutes"] },
  { name: "Hip Abduction Machine", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "hip_abductor", cues: ["Push the legs out against the pads", "Control the return, don't let it snap back"] },
  { name: "Band Lateral Walk", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["band"], loadingType: "distance", difficulty: 1, substitutionGroup: "hip_abductor", cues: ["Band around the thighs or ankles", "Small steps sideways, knees stay out over the toes"] },
  { name: "Clamshell", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["band"], loadingType: "external", difficulty: 1, substitutionGroup: "hip_abductor", cues: ["Lie on your side, knees bent", "Open the top knee without rolling the hips back"] },
  { name: "Standing Cable Hip Abduction", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["cable"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "hip_abductor", cues: ["Ankle cuff attached to a low cable", "Lift the leg out to the side, control the return"] },
  { name: "Band Standing Hip Abduction", primaryMuscle: "glutes", movementPattern: "isolation", equipment: ["band"], isUnilateral: true, loadingType: "external", difficulty: 1, substitutionGroup: "hip_abductor", cues: ["Band around the ankles or above the knees", "Lift the leg out to the side with control"] },
  { name: "Hip Adduction Machine", primaryMuscle: "adductors", movementPattern: "isolation", equipment: ["machine"], loadingType: "external", difficulty: 1, substitutionGroup: "hip_adductor", cues: ["Squeeze the legs together against the pads", "Control the return the whole way"] },
  { name: "Copenhagen Plank", primaryMuscle: "adductors", secondaryMuscles: ["core"], movementPattern: "isolation", equipment: ["bodyweight"], isUnilateral: true, loadingType: "time", difficulty: 4, substitutionGroup: "hip_adductor", contraindications: ["knee"], cues: ["Top leg rests on a bench, bottom leg hovers", "Hold a straight line through the hips"] },

  // --- Forearm isolation ---
  { name: "Wrist Curl", primaryMuscle: "forearms", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "forearm_isolation", contraindications: ["wrist"], cues: ["Forearms rest on a bench, palms up", "Curl the wrists up slowly"] },
  { name: "Reverse Wrist Curl", primaryMuscle: "forearms", movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "external", difficulty: 1, substitutionGroup: "forearm_isolation", contraindications: ["wrist"], cues: ["Forearms rest on a bench, palms down", "Curl the wrists up slowly against the weight"] },
  { name: "Dead Hang", primaryMuscle: "forearms", secondaryMuscles: ["back"], movementPattern: "isolation", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, substitutionGroup: "forearm_isolation", contraindications: ["shoulder"], cues: ["Relax the shoulders and just hang", "Breathe normally, don't hold your breath"] },
  { name: "Plate Pinch Hold", primaryMuscle: "forearms", movementPattern: "isolation", equipment: ["none"], loadingType: "time", difficulty: 2, substitutionGroup: "forearm_isolation", contraindications: ["wrist"], cues: ["Pinch two plates together smooth side out", "Stand tall, just hold, no need to move"] },
  { name: "Farmer's Hold", primaryMuscle: "forearms", secondaryMuscles: ["core"], movementPattern: "isolation", equipment: ["dumbbell"], loadingType: "time", difficulty: 1, substitutionGroup: "forearm_isolation", cues: ["Just stand and hold, tall posture", "Grip firm but relaxed through the shoulders"] },

  // --- Conditioning ---
  { name: "Treadmill Run", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "distance", difficulty: 2, cues: ["Find a pace you can hold steady", "Land softly, don't overstride"] },
  { name: "Stationary Bike", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "calories", difficulty: 1, cues: ["Seat height set so the knee is slightly bent at the bottom", "Keep a steady, even pace"] },
  { name: "Stair Climber", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "time", difficulty: 2, cues: ["Stand tall, avoid leaning on the rails", "Full steps rather than tiny quick ones"] },
  { name: "Ski Erg", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "calories", difficulty: 2, cues: ["Pull from the lats, not just the arms", "Hinge at the hips as you pull down"] },
  { name: "Jump Rope", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["none"], loadingType: "time", difficulty: 2, contraindications: ["knee"], cues: ["Small quiet jumps, just clearing the rope", "Keep the elbows close, turn the rope with the wrists"] },
  { name: "Burpees", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 3, contraindications: ["knee", "lower_back", "wrist", "pregnancy"], cues: ["Move at a pace you can sustain, not your fastest", "Step back instead of jumping if that's more comfortable"] },
  { name: "Mountain Climbers", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 2, contraindications: ["wrist"], cues: ["Keep the hips level, don't let them pike up", "Drive the knees in at a pace you control"] },
  { name: "Jumping Jacks", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, cues: ["Land soft on the balls of the feet", "Keep a steady rhythm"] },
  { name: "Box Jump", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 3, contraindications: ["knee", "pregnancy"], cues: ["Step down off the box, don't jump down", "Land soft with the knees slightly bent"] },
  { name: "Battle Ropes", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["none"], loadingType: "time", difficulty: 2, contraindications: ["shoulder"], cues: ["Alternate arms in a steady wave", "Keep the knees soft, brace the core"] },
  { name: "Sled Push", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["none"], loadingType: "distance", difficulty: 3, contraindications: ["lower_back", "pregnancy"], cues: ["Lean into it, drive with the legs", "Keep the back flat, don't round forward"] },
  { name: "Sled Drag", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["none"], loadingType: "distance", difficulty: 2, contraindications: ["lower_back"], cues: ["Short, quick steps work better than long strides", "Keep the chest up as you walk backward or forward"] },
  { name: "Kettlebell Snatch", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["kettlebell"], isUnilateral: true, loadingType: "time", difficulty: 5, contraindications: ["shoulder", "lower_back"], cues: ["Keep the bell close on the way up", "Punch through at the top rather than muscling it overhead"] },
  { name: "Kettlebell Clean and Press", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["kettlebell"], isUnilateral: true, loadingType: "time", difficulty: 4, contraindications: ["shoulder", "wrist"], cues: ["Keep the elbow tucked as the bell arrives at the shoulder", "Press overhead only once you're stable"] },
  { name: "Shadow Boxing", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, cues: ["Stay light on your feet", "Keep the hands up near the chin"] },
  { name: "Bear Crawl", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "distance", difficulty: 2, contraindications: ["wrist"], cues: ["Knees hover just off the floor", "Move the opposite hand and foot together"] },
  { name: "High Knees", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["bodyweight"], loadingType: "time", difficulty: 1, cues: ["Drive the knees up toward hip height", "Stay light and quick on the feet"] },
  { name: "Elliptical", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "time", difficulty: 1, cues: ["Keep a smooth, even stride", "Use the handles lightly, let the legs do the work"] },
  { name: "Versaclimber", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["machine"], loadingType: "time", difficulty: 3, cues: ["Opposite arm and leg reach together", "Keep the movement smooth rather than rushed"] },
  { name: "Thrusters", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["dumbbell"], loadingType: "time", difficulty: 4, contraindications: ["shoulder", "knee"], cues: ["Squat down, then drive the dumbbells overhead as you stand", "Let the leg drive power the press, not just the arms"] },
  { name: "Devil Press", primaryMuscle: "full_body", movementPattern: "conditioning", equipment: ["dumbbell"], loadingType: "time", difficulty: 5, contraindications: ["shoulder", "lower_back"], cues: ["Burpee into a swing that finishes overhead", "Pace yourself, this one adds up fast"] },
];
